# Generated by Django 2.0.13 on 2019-04-26 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('content', models.BinaryField(blank=True, default=None, null=True)),
                ('mimetype', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('from_email', models.CharField(blank=True, default='', max_length=255)),
                ('to_emails', models.TextField(blank=True, default='')),
                ('cc_emails', models.TextField(blank=True, default='')),
                ('bcc_emails', models.TextField(blank=True, default='')),
                ('all_recipients', models.TextField(blank=True, default='')),
                ('headers', models.TextField(blank=True, default='')),
                ('subject', models.TextField(blank=True, default='')),
                ('body', models.TextField(blank=True, default='')),
                ('raw', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AddField(
            model_name='attachment',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='database_email_backend.Email'),
        ),
        migrations.CreateModel(
            name='SendEmail',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('database_email_backend.email',),
        ),
    ]
